name: ImageLib
description: 2D image effects library
version: 2.12.0
homepage: https://github.com/FarragoFiction/ImageLib
author: paradoxLands
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
